version: '3.3'
services:

  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend
    expose:
      - 8000
    restart: always
    volumes:
      # - static_value:/app/static/
      - images:/app/images/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build: ../frontend
    volumes:
      - static:/app/dist/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      # - ../docs/:/usr/share/nginx/html/api/docs/
      - images:/var/html/images/
    env_file:
      - ./.env
    depends_on:
      - frontend
       
volumes:
  static:
  images:
  pg_data: