version: '3.3'
services:

  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: zoochecker:latest
    expose:
      - 8000
    restart: always
    volumes:
      # - static_value:/app/static/
      - media_value:/app/images/
    depends_on:
      - db
    env_file:
      - ./.env

  # frontend:
  #   image: basicshade/foodgram_frontend:latest
  #   volumes:
  #     - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      # - ../docs/:/usr/share/nginx/html/api/docs/
      # - static_value:/var/html/static/
      - media_value:/var/html/images/
    depends_on:
      - frontend

volumes:
  # static_value:
  media_value:
  pg_data: