"""change field to jsonb

Revision ID: 0a7700677d75
Revises: c9fb40bf8669
Create Date: 2023-02-15 15:39:18.340555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7700677d75'
down_revision = 'c9fb40bf8669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
