"""add receipt and image models

Revision ID: 578cb6a742c6
Revises: 
Create Date: 2023-02-13 18:41:04.396355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578cb6a742c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=42, cycle=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_image',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('receipt_id', 'width', 'height')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_image')
    op.drop_table('receipt')
    # ### end Alembic commands ###
