"""change status to success

Revision ID: c9fb40bf8669
Revises: 578cb6a742c6
Create Date: 2023-02-15 14:42:54.198746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fb40bf8669'
down_revision = '578cb6a742c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('success', sa.Boolean(), nullable=False))
    op.drop_column('receipt', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_column('receipt', 'success')
    # ### end Alembic commands ###
