"""change field to jsonb

Revision ID: f66c3d37f906
Revises: 0a7700677d75
Create Date: 2023-02-15 15:41:52.678618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66c3d37f906'
down_revision = '0a7700677d75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
